package Xample.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Column = 0;
  public static final int ConceptHub = 1;
  public static final int Entity = 2;
  public static final int Page = 3;
  public static final int System = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb3a9720d85244c66L, 0x8267f2e44e0f706fL);
    builder.put(0x488c7cdcd4cf496fL, Column);
    builder.put(0x488c7cdcd4cfd3a9L, ConceptHub);
    builder.put(0x488c7cdcd4cf4962L, Entity);
    builder.put(0x488c7cdcd4cf4965L, Page);
    builder.put(0x488c7cdcd4cf495fL, System);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
