package Glot.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Attribute = 0;
  public static final int Element = 1;
  public static final int Entity = 2;
  public static final int Feature = 3;
  public static final int Form = 4;
  public static final int Page = 5;
  public static final int Reference = 6;
  public static final int System = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x28e4957b85994380L, 0x9a2de36d611c13b9L);
    builder.put(0x1f05a1bb5d897c30L, Attribute);
    builder.put(0x34b196dfcc949dc3L, Element);
    builder.put(0x1f05a1bb5d897c26L, Entity);
    builder.put(0x1f05a1bb5d897c2bL, Feature);
    builder.put(0x34b196dfcc949dc0L, Form);
    builder.put(0x34b196dfcc93680fL, Page);
    builder.put(0x1f05a1bb5d897c41L, Reference);
    builder.put(0x1f05a1bb5d897c23L, System);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
